### PR TITLE
Custom span decorators

### PR DESCRIPTION
**Pull request by crisbodnar**
Adds decorators for Server and Client Interceptors.

### CODE REVIEW

**Comment by malafeev** [comment]
Thank you @crisbodnar 
Please update also README

**Comment by crisbodnar** [comment]
Done @malafeev

**Comment by crisbodnar** [comment]
@malafeev Any timeline for when is this going to be released so we can start using it?

**Comment by malafeev** [comment]
tomorrow morning :)

**Comment by malafeev** [comment]
I already released it, but in maven central new version will come in several hours (usually 12 hours is enough)

**Pull request merged**
